name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: gopal
          POSTGRES_PASSWORD: gopal
          POSTGRES_DB: hronboardinglanggraphdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10 # ✅ Changed from 3.1 or 3.13 to supported 3.10

      # Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run linting
      - name: Run Linting
        working-directory: backend
        run: |
          pip install flake8
          flake8 .

      # Run tests
      - name: Run Tests
        working-directory: backend
        run: |
          pytest

      # Docker build test
      - name: Docker Build
        run: |
          docker build -t hr-onboarding-backend ./backend
