name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: gopal
          POSTGRES_PASSWORD: gopal
          POSTGRES_DB: hronboardinglanggraphdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linting
        working-directory: backend
        run: |
          pip install flake8
          flake8 .

      - name: Run Tests
        working-directory: backend
        run: |
          pytest

      - name: Docker build test
        run: |
          docker build -t hr-onboarding-backend ./backend
